name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: FlyStay
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2'
    - uses: actions/checkout@v4
    - name: Copy .env
      run:  |
        php -r "file_exists('.env') || copy('.env.example', '.env');"
        echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET }}" >> .env
        echo "STRIPE_PUBLIC_KEY=${{ secrets.STRIPE_KEY }}" >> .env
        php artisan key:generate
        php artisan jwt:secret --force
      
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
      
    - name: Wait for MySQL
      run: |
        until mysqladmin ping -h 127.0.0.1 -P 3306 --silent; do
          echo "Waiting for MySQL..."
          sleep 3
        done

    - name: Run Migrations refresh
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: FlyStay
        DB_USERNAME: root
        DB_PASSWORD: root
      run: php artisan migrate:refresh

    - name: Run Country Seeder
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: FlyStay
        DB_USERNAME: root
        DB_PASSWORD: root
      run: php artisan db:seed --class=CountrySeeder

    - name: Import Airports
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: FlyStay
        DB_USERNAME: root
        DB_PASSWORD: root
      run: php artisan app:import-airports

    - name: Run Seeders
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: FlyStay
        DB_USERNAME: root
        DB_PASSWORD: root
      run: php artisan db:seed

    - name: Execute Tests
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: FlyStay
        DB_USERNAME: root
        DB_PASSWORD: root
      run: php artisan test
