name: Laravel

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: FlyStay
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
    - uses: actions/checkout@v4

    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, pdo, pdo_mysql

      
    - name: Copy .env and set secrets
      run: |
        cp .env.example .env
        echo "STRIPE_SECRET=${{ secrets.STRIPE_SECRET }}" >> .env
        echo "STRIPE_KEY=${{ secrets.STRIPE_KEY }}" >> .env
        echo "VIRUSTOTAL_API_KEY=${{ secrets.VIRUSTOTAL_API_KEY }}" >> .env
        echo "WEATHER_APP_KEY=${{ secrets.WEATHER_APP_KEY }}" >> .env
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=127.0.0.1" >> .env
        echo "DB_PORT=3306" >> .env
        echo "DB_DATABASE=FlyStay" >> .env
        echo "DB_USERNAME=root" >> .env
        echo "DB_PASSWORD=root" >> .env

    - name: Install Composer Dependencies
      run: composer install --no-interaction --prefer-dist
      
    - name: Generate Keys
      run: |
        php artisan key:generate
        php artisan jwt:secret --force

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Wait for MySQL
      run: |
        until mysqladmin ping -h 127.0.0.1 -P 3306 --silent; do
          echo "Waiting for MySQL..."
          sleep 3
        done

    - name: Run Application 
      run: |
        php artisan migrate:refresh
        php artisan db:seed --class=CountrySeeder
        php artisan app:import-airports
        php artisan db:seed

    - name: Run All Tests
      run: php artisan test --verbose
